//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Locals {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locals() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Recipes_application.Views.Locals", typeof(Locals).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quantity is required.
        /// </summary>
        internal static string IngedientModel_Quantity_Required {
            get {
                return ResourceManager.GetString("IngedientModel_Quantity_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity:.
        /// </summary>
        internal static string IngredientModel_Quantity {
            get {
                return ResourceManager.GetString("IngredientModel_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        internal static string IngredientModel_Title {
            get {
                return ResourceManager.GetString("IngredientModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title is required.
        /// </summary>
        internal static string IngredientModel_Title_Required {
            get {
                return ResourceManager.GetString("IngredientModel_Title_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity:.
        /// </summary>
        internal static string ProductModel_Quantity {
            get {
                return ResourceManager.GetString("ProductModel_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        internal static string ProductModel_Title {
            get {
                return ResourceManager.GetString("ProductModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price:.
        /// </summary>
        internal static string ProductStoreModel_Price {
            get {
                return ResourceManager.GetString("ProductStoreModel_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity:.
        /// </summary>
        internal static string ProductStoreModel_Quantity {
            get {
                return ResourceManager.GetString("ProductStoreModel_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooking time:.
        /// </summary>
        internal static string RecipeModel_CookingTime {
            get {
                return ResourceManager.GetString("RecipeModel_CookingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients:.
        /// </summary>
        internal static string RecipeModel_Ingredients {
            get {
                return ResourceManager.GetString("RecipeModel_Ingredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recipe&apos;s ingredients are required.
        /// </summary>
        internal static string RecipeModel_Ingredients_Required {
            get {
                return ResourceManager.GetString("RecipeModel_Ingredients_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparation time:.
        /// </summary>
        internal static string RecipeModel_PreparationTime {
            get {
                return ResourceManager.GetString("RecipeModel_PreparationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe&apos;s steps:.
        /// </summary>
        internal static string RecipeModel_Steps {
            get {
                return ResourceManager.GetString("RecipeModel_Steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        internal static string RecipeModel_Title {
            get {
                return ResourceManager.GetString("RecipeModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recipe&apos;s title is required.
        /// </summary>
        internal static string RecipeModel_Title_Required {
            get {
                return ResourceManager.GetString("RecipeModel_Title_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        internal static string StoreModel_City {
            get {
                return ResourceManager.GetString("StoreModel_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The store&apos;s city is required.
        /// </summary>
        internal static string StoreModel_City_Required {
            get {
                return ResourceManager.GetString("StoreModel_City_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string StoreModel_Name {
            get {
                return ResourceManager.GetString("StoreModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The store&apos;s name is required.
        /// </summary>
        internal static string StoreModel_Name_Required {
            get {
                return ResourceManager.GetString("StoreModel_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone:.
        /// </summary>
        internal static string StoreModel_Phone {
            get {
                return ResourceManager.GetString("StoreModel_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone number.
        /// </summary>
        internal static string StoreModel_Phone_RegularExpression {
            get {
                return ResourceManager.GetString("StoreModel_Phone_RegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The store&apos;s phone is required.
        /// </summary>
        internal static string StoreModel_Phone_Required {
            get {
                return ResourceManager.GetString("StoreModel_Phone_Required", resourceCulture);
            }
        }
    }
}
